# App Properties
bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000

server:
  port: 9090
spring:
  datasource:
    url: jdbc:sqlite:/teach/run/java.db
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: admin
  jpa:
    database-platform: org.fatmansoft.teach.sqlite.SQLDialect
    generate-ddl: true
    hibernate.ddl-auto: update
#  datasource:
#    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=GMT%2B8
#    username: root
#    password: Sdu2022.
#    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    addresses: localhost
    username: admin
    password: admin
    virtual-host: /
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jmx:
    enabled: false

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

attach:
  folder: /teach/run/


#spring.datasource.url = jdbc:sqlite:D:/teach/run/java.db
#spring.datasource.driver-class-name = org.sqlite.JDBC
#spring.datasource.username = admin
#spring.datasource.password = admin
#spring.jpa.generate-ddl=true





